Revise building inside chroot.
Improved documentation and error messages. Also specified more fonts in correct
names.

BUG=chrome-os-partner:30960
TEST=manual: make x86-generic arm-generic

Change-Id: I00291082094f65532e99d351f52022444cf869cf
Reviewed-on: https://chrome-internal-review.googlesource.com/170661
Reviewed-by: Bowgo Tsai <bowgotsai@google.com>
Commit-Queue: Hung-Te Lin <hungte@google.com>
Tested-by: Hung-Te Lin <hungte@google.com>

diff --git a/strings/text_to_png_svg b/strings/text_to_png_svg
--- a/strings/text_to_png_svg
+++ b/strings/text_to_png_svg
@@ -44,7 +44,7 @@ while true ; do
                       fi
                     done)"
       if [ -n "${font_params}" -a -z "${found_font}" ]; then
-        echo "ERROR: Missing font ${font_params}."
+        echo "ERROR: Missing font ${font_params}." >&2
         exit 1
       fi
       font="${found_font}"
