bmpblk: Change to board-friendly building procedure.
To support better firmware bitmap customization in future, we're moving from
"dimension-based profiles" to board names.

Also refined build instruction and fixed font-related issues (missing fonts,
and make arrow glyphs to be generated by Unicode fonts).

BUG=none
TEST=make # success.

Change-Id: I3ba9c6c2b27eece9a84bf438a151ffbc6419e52e
Reviewed-on: https://gerrit-int.chromium.org/29059
Reviewed-by: Bill Richardson <wfrichar@google.com>
Commit-Ready: Hung-Te Lin <hungte@google.com>
Tested-by: Hung-Te Lin <hungte@google.com>

diff --git a/strings/text_to_png b/strings/text_to_png
--- a/strings/text_to_png
+++ b/strings/text_to_png
@@ -36,6 +36,10 @@ while true ; do
       param="${1##*=}"
       # TODO(hungte) support "+XXX" = add font description (ex, BOLD).
       [ -n "$param" ] && font="$param"
+      if ! fc-list -q "$param"; then
+        echo "ERROR: Missing font $param."
+        exit 1
+      fi
       shift
       ;;
     --align=*)
